In [15]:
import pandas as pd

df = pd.read_csv(
    'shoporders.csv',
    sep=',',
    encoding='utf-8',
    decimal='.',
    parse_dates=['order_date']
)

df

,order_id,customer_name,product,category,quantity,unit,price,currency,order_date,shipping_country,payment_method
0,1150,Markus Frei,Aktenordner,Büro,1,Stück,9.41,CHF,2024-07-18,Schweiz,Kreditkarte
1,1002,Stefan Wagner,Laptop,Elektro,1,Stück,813.87,CHF,2024-08-02,Italien,Twint
2,1158,Nicole Gerber,Springseil,Sport,4,Stück,16.23,CHF,2024-07-05,Deutschland,PayPal
3,1052,Laura Zimmermann,Trinkflasche,Sport,4,Stück,21.09,CHF,2024-04-22,NaN,Twint
4,1138,Julia Fischer,Laufschuhe,Sport,5,Stück,120.10,CHF,2024-04-02,Switzerlaand,Rechnung
...,...,...,...,...,...,...,...,...,...,...,...
207,1034,Thomas Bauer,Tablet,Elektro,5,Stück,408.63,CHF,2024-03-24,Deutschland,Twint
208,1117,Michael Braun,Taschenrechner,Büro,5,Stück,19.32,EUR,2024-01-27,Frankreich,Rechnung
209,1015,Lukas Brunner,Drucker,Büro,1,Stück,272.80,CHF,2024-03-06,Deutschland,Twint
210,1030,Monika Lehmann,Smartphone,Elektro,3,Stück,807.51,EUR,2024-04-17,Italien,Rechnung
211,1115,NaN,Schuhe,Mode,3,Stück,94.03,CHF,2024-12-06,Österreich,Rechnung

In [16]:
# Aufgabe 1, Spalte payment_method in One-Hot-Encoding umwandeln
df = pd.get_dummies(df, columns=['payment_method'], prefix='pay')
df

,order_id,customer_name,product,category,quantity,unit,price,currency,order_date,shipping_country,pay_Kreditkarte,pay_PayPal,pay_Rechnung,pay_Twint
0,1150,Markus Frei,Aktenordner,Büro,1,Stück,9.41,CHF,2024-07-18,Schweiz,True,False,False,False
1,1002,Stefan Wagner,Laptop,Elektro,1,Stück,813.87,CHF,2024-08-02,Italien,False,False,False,True
2,1158,Nicole Gerber,Springseil,Sport,4,Stück,16.23,CHF,2024-07-05,Deutschland,False,True,False,False
3,1052,Laura Zimmermann,Trinkflasche,Sport,4,Stück,21.09,CHF,2024-04-22,NaN,False,False,False,True
4,1138,Julia Fischer,Laufschuhe,Sport,5,Stück,120.10,CHF,2024-04-02,Switzerlaand,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,1034,Thomas Bauer,Tablet,Elektro,5,Stück,408.63,CHF,2024-03-24,Deutschland,False,False,False,True
208,1117,Michael Braun,Taschenrechner,Büro,5,Stück,19.32,EUR,2024-01-27,Frankreich,False,False,True,False
209,1015,Lukas Brunner,Drucker,Büro,1,Stück,272.80,CHF,2024-03-06,Deutschland,False,False,False,True
210,1030,Monika Lehmann,Smartphone,Elektro,3,Stück,807.51,EUR,2024-04-17,Italien,False,False,True,False
211,1115,NaN,Schuhe,Mode,3,Stück,94.03,CHF,2024-12-06,Österreich,False,False,True,False

In [17]:
# Aufgabe 2, Spalte order_date in weekday, month und is_weekend umwandeln
df['order_date'] = pd.to_datetime(df['order_date'])
df['weekday'] = df['order_date'].dt.dayofweek + 1
df['month'] = df['order_date'].dt.month
df['is_weekend'] = df['weekday'].isin([6, 7])
df

,order_id,customer_name,product,category,quantity,unit,price,currency,order_date,shipping_country,pay_Kreditkarte,pay_PayPal,pay_Rechnung,pay_Twint,weekday,month,is_weekend
0,1150,Markus Frei,Aktenordner,Büro,1,Stück,9.41,CHF,2024-07-18,Schweiz,True,False,False,False,4,7,False
1,1002,Stefan Wagner,Laptop,Elektro,1,Stück,813.87,CHF,2024-08-02,Italien,False,False,False,True,5,8,False
2,1158,Nicole Gerber,Springseil,Sport,4,Stück,16.23,CHF,2024-07-05,Deutschland,False,True,False,False,5,7,False
3,1052,Laura Zimmermann,Trinkflasche,Sport,4,Stück,21.09,CHF,2024-04-22,NaN,False,False,False,True,1,4,False
4,1138,Julia Fischer,Laufschuhe,Sport,5,Stück,120.10,CHF,2024-04-02,Switzerlaand,False,False,True,False,2,4,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,1034,Thomas Bauer,Tablet,Elektro,5,Stück,408.63,CHF,2024-03-24,Deutschland,False,False,False,True,7,3,True
208,1117,Michael Braun,Taschenrechner,Büro,5,Stück,19.32,EUR,2024-01-27,Frankreich,False,False,True,False,6,1,True
209,1015,Lukas Brunner,Drucker,Büro,1,Stück,272.80,CHF,2024-03-06,Deutschland,False,False,False,True,3,3,False
210,1030,Monika Lehmann,Smartphone,Elektro,3,Stück,807.51,EUR,2024-04-17,Italien,False,False,True,False,3,4,False
211,1115,NaN,Schuhe,Mode,3,Stück,94.03,CHF,2024-12-06,Österreich,False,False,True,False,5,12,False

In [ ]:
# Aufgabe 3, Verhältnis Feature
df['price_per_unit'] = df['price'] / df['quantity']
df

,order_id,customer_name,product,category,quantity,unit,price,currency,order_date,shipping_country,pay_Kreditkarte,pay_PayPal,pay_Rechnung,pay_Twint,weekday,month,is_weekend,price_per_unit
0,1150,Markus Frei,Aktenordner,Büro,1,Stück,9.41,CHF,2024-07-18,Schweiz,True,False,False,False,4,7,False,9.410000
1,1002,Stefan Wagner,Laptop,Elektro,1,Stück,813.87,CHF,2024-08-02,Italien,False,False,False,True,5,8,False,813.870000
2,1158,Nicole Gerber,Springseil,Sport,4,Stück,16.23,CHF,2024-07-05,Deutschland,False,True,False,False,5,7,False,4.057500
3,1052,Laura Zimmermann,Trinkflasche,Sport,4,Stück,21.09,CHF,2024-04-22,NaN,False,False,False,True,1,4,False,5.272500
4,1138,Julia Fischer,Laufschuhe,Sport,5,Stück,120.10,CHF,2024-04-02,Switzerlaand,False,False,True,False,2,4,False,24.020000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,1034,Thomas Bauer,Tablet,Elektro,5,Stück,408.63,CHF,2024-03-24,Deutschland,False,False,False,True,7,3,True,81.726000
208,1117,Michael Braun,Taschenrechner,Büro,5,Stück,19.32,EUR,2024-01-27,Frankreich,False,False,True,False,6,1,True,3.864000
209,1015,Lukas Brunner,Drucker,Büro,1,Stück,272.80,CHF,2024-03-06,Deutschland,False,False,False,True,3,3,False,272.800000
210,1030,Monika Lehmann,Smartphone,Elektro,3,Stück,807.51,EUR,2024-04-17,Italien,False,False,True,False,3,4,False,269.170000
211,1115,NaN,Schuhe,Mode,3,Stück,94.03,CHF,2024-12-06,Österreich,False,False,True,False,5,12,False,31.343333

In [ ]:
# Aufgabe 4, Numerische Spalte skalieren
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df['price_scaled'] = scaler.fit_transform(df[['price']])
df

,order_id,customer_name,product,category,quantity,unit,price,currency,order_date,shipping_country,pay_Kreditkarte,pay_PayPal,pay_Rechnung,pay_Twint,weekday,month,is_weekend,price_per_unit,price_scaled
0,1150,Markus Frei,Aktenordner,Büro,1,Stück,9.41,CHF,2024-07-18,Schweiz,True,False,False,False,4,7,False,9.410000,-0.561051
1,1002,Stefan Wagner,Laptop,Elektro,1,Stück,813.87,CHF,2024-08-02,Italien,False,False,False,True,5,8,False,813.870000,2.678584
2,1158,Nicole Gerber,Springseil,Sport,4,Stück,16.23,CHF,2024-07-05,Deutschland,False,True,False,False,5,7,False,4.057500,-0.533587
3,1052,Laura Zimmermann,Trinkflasche,Sport,4,Stück,21.09,CHF,2024-04-22,NaN,False,False,False,True,1,4,False,5.272500,-0.514015
4,1138,Julia Fischer,Laufschuhe,Sport,5,Stück,120.10,CHF,2024-04-02,Switzerlaand,False,False,True,False,2,4,False,24.020000,-0.115292
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,1034,Thomas Bauer,Tablet,Elektro,5,Stück,408.63,CHF,2024-03-24,Deutschland,False,False,False,True,7,3,True,81.726000,1.046645
208,1117,Michael Braun,Taschenrechner,Büro,5,Stück,19.32,EUR,2024-01-27,Frankreich,False,False,True,False,6,1,True,3.864000,-0.521143
209,1015,Lukas Brunner,Drucker,Büro,1,Stück,272.80,CHF,2024-03-06,Deutschland,False,False,False,True,3,3,False,272.800000,0.499645
210,1030,Monika Lehmann,Smartphone,Elektro,3,Stück,807.51,EUR,2024-04-17,Italien,False,False,True,False,3,4,False,269.170000,2.652972
211,1115,NaN,Schuhe,Mode,3,Stück,94.03,CHF,2024-12-06,Österreich,False,False,True,False,5,12,False,31.343333,-0.220279

In [ ]:
# Aufgabe 5, Werte Binnen
labels = ['<= 10', '11-50', '50-100', '100-200', '200-500', '> 500']
bins = [0, 11, 51, 101, 201, 501, 100000000]
df['price_binned'] = pd.cut(df['price'], bins=bins, labels=labels)
df

,order_id,customer_name,product,category,quantity,unit,price,currency,order_date,shipping_country,...,pay_PayPal,pay_Rechnung,pay_Twint,weekday,month,is_weekend,price_per_unit,price_scaled,price_log,price_binned
0,1150,Markus Frei,Aktenordner,Büro,1,Stück,9.41,CHF,2024-07-18,Schweiz,...,False,False,False,4,7,False,9.410000,-0.561051,2.342767,<= 10
1,1002,Stefan Wagner,Laptop,Elektro,1,Stück,813.87,CHF,2024-08-02,Italien,...,False,False,True,5,8,False,813.870000,2.678584,6.703029,> 500
2,1158,Nicole Gerber,Springseil,Sport,4,Stück,16.23,CHF,2024-07-05,Deutschland,...,True,False,False,5,7,False,4.057500,-0.533587,2.846652,11-50
3,1052,Laura Zimmermann,Trinkflasche,Sport,4,Stück,21.09,CHF,2024-04-22,NaN,...,False,False,True,1,4,False,5.272500,-0.514015,3.095125,11-50
4,1138,Julia Fischer,Laufschuhe,Sport,5,Stück,120.10,CHF,2024-04-02,Switzerlaand,...,False,True,False,2,4,False,24.020000,-0.115292,4.796617,100-200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,1034,Thomas Bauer,Tablet,Elektro,5,Stück,408.63,CHF,2024-03-24,Deutschland,...,False,False,True,7,3,True,81.726000,1.046645,6.015254,200-500
208,1117,Michael Braun,Taschenrechner,Büro,5,Stück,19.32,EUR,2024-01-27,Frankreich,...,False,True,False,6,1,True,3.864000,-0.521143,3.011606,11-50
209,1015,Lukas Brunner,Drucker,Büro,1,Stück,272.80,CHF,2024-03-06,Deutschland,...,False,False,True,3,3,False,272.800000,0.499645,5.612398,200-500
210,1030,Monika Lehmann,Smartphone,Elektro,3,Stück,807.51,EUR,2024-04-17,Italien,...,False,True,False,3,4,False,269.170000,2.652972,6.695193,> 500
211,1115,NaN,Schuhe,Mode,3,Stück,94.03,CHF,2024-12-06,Österreich,...,False,True,False,5,12,False,31.343333,-0.220279,4.554193,50-100

In [ ]:
# Aufgabe 6,Gruppenbasierte Aggregation
df['customer_avg_order'] = (df.groupby('customer_name')['price'].transform('mean'))
df

,order_id,customer_name,product,category,quantity,unit,price,currency,order_date,shipping_country,...,pay_Rechnung,pay_Twint,weekday,month,is_weekend,price_per_unit,price_scaled,price_log,price_binned,customer_avg_order
0,1150,Markus Frei,Aktenordner,Büro,1,Stück,9.41,CHF,2024-07-18,Schweiz,...,False,False,4,7,False,9.410000,-0.561051,2.342767,<= 10,140.772500
1,1002,Stefan Wagner,Laptop,Elektro,1,Stück,813.87,CHF,2024-08-02,Italien,...,False,True,5,8,False,813.870000,2.678584,6.703029,> 500,125.583000
2,1158,Nicole Gerber,Springseil,Sport,4,Stück,16.23,CHF,2024-07-05,Deutschland,...,False,False,5,7,False,4.057500,-0.533587,2.846652,11-50,51.799167
3,1052,Laura Zimmermann,Trinkflasche,Sport,4,Stück,21.09,CHF,2024-04-22,NaN,...,False,True,1,4,False,5.272500,-0.514015,3.095125,11-50,60.915455
4,1138,Julia Fischer,Laufschuhe,Sport,5,Stück,120.10,CHF,2024-04-02,Switzerlaand,...,True,False,2,4,False,24.020000,-0.115292,4.796617,100-200,187.970000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207,1034,Thomas Bauer,Tablet,Elektro,5,Stück,408.63,CHF,2024-03-24,Deutschland,...,False,True,7,3,True,81.726000,1.046645,6.015254,200-500,195.093000
208,1117,Michael Braun,Taschenrechner,Büro,5,Stück,19.32,EUR,2024-01-27,Frankreich,...,True,False,6,1,True,3.864000,-0.521143,3.011606,11-50,235.135000
209,1015,Lukas Brunner,Drucker,Büro,1,Stück,272.80,CHF,2024-03-06,Deutschland,...,False,True,3,3,False,272.800000,0.499645,5.612398,200-500,141.573636
210,1030,Monika Lehmann,Smartphone,Elektro,3,Stück,807.51,EUR,2024-04-17,Italien,...,True,False,3,4,False,269.170000,2.652972,6.695193,> 500,210.205000
211,1115,NaN,Schuhe,Mode,3,Stück,94.03,CHF,2024-12-06,Österreich,...,True,False,5,12,False,31.343333,-0.220279,4.554193,50-100,NaN

In [ ]:
# Aufgabe 7, Log Transformation
import numpy as np
df['price_log'] = np.log1p(df['price'])
df